# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "#about"
    weight: 1
  - name: Projects
    url: "#projects"
    weight: 2
  - name: Publications
    url: "#publications"
    weight: 3
  - name: Talks
    url: "#talks_favorite"
    weight: 4
  - name: Blog
    url: "#blog"
    weight: 5
  - name: CV
    url: "#cv"
    weight: 6
  - name: Mentoring
    url: "#mentoring"
    weight: 7
  - name: Teaching
    url: "#teaching"
    weight: 8
  - name: Contact
    url: "#contact"
    weight: 9

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70