# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Principal
    url: "#about"
    weight: 1
  - name: Equipo
    url: "#team"
    weight: 2
  - name: Proyectos
    url: "#projects"
    weight: 3
  - name: Publicaciones
    url: "#publications"
    weight: 4
  - name: Presentaciones
    url: "#talks"
    weight: 5
  - name: Blog
    url: "#blog"
    weight: 6
  - name: Cursos
    url: "#teaching"
    weight: 7
  - name: CV
    url: "#cv"
    weight: 8
  - name: Contacto
    url: "#contact"
    weight: 9

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
